version: '3.8'

services:
  app:
    build: .
    container_name: tg_reminder
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env  
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      retries: 5

volumes:
  pg_data:
